CREATE TYPE "public"."form_submission_kind" AS ENUM('audit', 'contact');--> statement-breakpoint
CREATE TYPE "public"."form_submission_status" AS ENUM('in_progress', 'abandoned', 'completed', 'captured');--> statement-breakpoint
CREATE TABLE "form_submissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" "form_submission_kind" NOT NULL,
	"session_key" text NOT NULL,
	"status" "form_submission_status" NOT NULL,
	"last_trigger" text,
	"source_detail" text NOT NULL,
	"started_at" timestamp with time zone NOT NULL,
	"last_activity_at" timestamp with time zone NOT NULL,
	"completed_at" timestamp with time zone,
	"captured_at" timestamp with time zone,
	"duration_ms" integer,
	"furthest_step_index" integer,
	"steps_total" integer,
	"answered_count" integer,
	"questions_total" integer,
	"percent_complete" integer,
	"responses" jsonb,
	"result" jsonb,
	"phase_id" text,
	"top_service_id" text,
	"contact_name" text,
	"contact_email" text,
	"contact_company" text,
	"contact_website" text,
	"message" text,
	"marketing_consent" boolean,
	"posthog_distinct_id" text,
	"posthog_session_id" text,
	"posthog_replay_url" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"utm_term" text,
	"utm_content" text,
	"gclid" text,
	"referrer" text,
	"landing_path" text,
	"viewport" text,
	"screen_width" integer,
	"timezone" text,
	"language" text,
	"user_agent" text,
	"created_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
	"updated_at" timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "form_submissions_session_key_key" UNIQUE("session_key")
);
--> statement-breakpoint
CREATE INDEX "idx_form_submissions_kind_status" ON "form_submissions" USING btree ("kind" enum_ops,"status" enum_ops) WHERE (deleted_at IS NULL);--> statement-breakpoint
CREATE INDEX "idx_form_submissions_last_activity_at" ON "form_submissions" USING btree ("last_activity_at" DESC NULLS LAST) WHERE (deleted_at IS NULL);--> statement-breakpoint
CREATE INDEX "idx_form_submissions_contact_email" ON "form_submissions" USING btree ("contact_email" text_ops) WHERE (deleted_at IS NULL AND contact_email IS NOT NULL);