export { saveLead, type SaveLeadInput } from './save-lead'
export { moveLead, type MoveLeadInput } from './move-lead'
export { archiveLead, type ArchiveLeadInput } from './archive-lead'
export { createLeadEmail, type CreateLeadEmailInput, type CreateLeadEmailResult } from './create-lead-email'
export { scheduleMeeting, type ScheduleMeetingInput, type ScheduleMeetingResult } from './schedule-meeting'
export { createProposal, type CreateProposalInput, type CreateProposalResult } from './create-proposal'
export { buildProposalFromScratch, type BuildProposalFromScratchInput, type BuildProposalFromScratchResult } from './build-proposal-from-scratch'
export { updateProposalStatus, type UpdateProposalStatusInput } from './update-proposal-status'
export { createLeadTask, type CreateLeadTaskInput, type CreateLeadTaskResult } from './create-lead-task'
export { rescoreLead, type RescoreLeadInput, type RescoreLeadResult } from './rescore-lead'
export { prepareProposalSend, type PrepareProposalSendInput, type PrepareProposalSendResult } from './prepare-proposal-send'
export { deleteProposalAction, type DeleteProposalInput, type DeleteProposalResult } from './delete-proposal'
export { updateProposalContent, type UpdateProposalContentInput, type UpdateProposalContentResult } from './update-proposal-content'
export { type LeadActionResult } from './types'
