export { saveContactMutation } from './save-contact'
export { softDeleteContactMutation } from './soft-delete-contact'
export { restoreContactMutation } from './restore-contact'
export { destroyContactMutation } from './destroy-contact'
export type { ContactMutationContext, ContactMutationResult } from './types'
