export { saveContactMutation } from './save-contact'
export { softDeleteContactMutation } from './soft-delete-contact'
export { restoreContactMutation } from './restore-contact'
export { destroyContactMutation } from './destroy-contact'
export { inviteContactToPortalMutation } from './invite-to-portal'
export { promoteContactToUserMutation } from './promote-to-user'
export type { PromoteToUserInput } from './promote-to-user'
export type { ContactMutationContext, ContactMutationResult } from './types'
