export { saveContactMutation } from './save-contact'
export { softDeleteContactMutation } from './soft-delete-contact'
export { restoreContactMutation } from './restore-contact'
export { destroyContactMutation } from './destroy-contact'
export { inviteContactToPortalMutation } from './invite-to-portal'
export { promoteContactToClientMutation } from './promote-to-client'
export type { PromoteToClientInput } from './promote-to-client'
export type { ContactMutationContext, ContactMutationResult } from './types'
